LoyaltyNZ/hoodoo

- Gemfile.lock
- hoodoo.gemspec
- lib/hoodoo/version.rb
Since 1.0.0 was pushed, 1.0.1 must be produced; 1.0.0 yanked from RubyGems for good measure.
> Authors change; previous list looked daft in RubyGems GUI

- spec/active/active_record/finder_spec.rb
…for single line strings built in the test suite over multiple lines of source code for legibility. This is faster and will play well with frozen-by-default string literals.
> Switch from method '<<' to interpreter-handled '\'

- lib/hoodoo/services/services/session.rb
Via @thelollies who pointed out this was happening in the Session module when reviewing a recent PR.
> Don't rescue Exception explicitly; rescue StandardError implicitly

- lib/hoodoo/services/middleware/amqp_log_writer.rb
- lib/hoodoo/services/middleware/middleware.rb
- lib/hoodoo/services/services/session.rb
- spec/services/middleware/amqp_log_writer_spec.rb
- spec/services/middleware/middleware_logging_spec.rb
Introduces a "verbose" option for logging (default off, omits heavy duty sections of the session information) and includes field `caller_identity_name`, a generic scoping name concept from Alchemy.
* Refactored to always generate the UUID in `id` at logging source rather than only in the Alchemy writer, so it's consistent across all log sinks.
* Common log payload data generation refactored into private middleware method `build_common_log_data_for`.
Note subtle arising fix in AMQP log writer where it used to force a value into `data`, but that Hash is passed by reference; so if any other loggers were in the pool afterwards, they'd acquire the value, but loggers in the queue beforehand would not see it.
> Logging improvements

- CHANGELOG.md
- Gemfile.lock
- docs/rdoc/classes/Hoodoo.html
- docs/rdoc/created.rid
- hoodoo.gemspec
- lib/hoodoo/monkey/patch/newrelic_traced_amqp.rb
- lib/hoodoo/version.rb
Under edge case conditions such as a service ActiveRecord migration that required 'hoodoo/active', the patch might get invoked but full middleware would not be available. No spec coverage for the 'negative' case because if undefined it simply won't proceed, but the line is run in the 'positive' case as part of the existing test coverage.
> Add a 'respond_to?' check for the cross-application tracing patch

- lib/hoodoo/monkey/patch/newrelic_traced_amqp.rb
NewRelic cross-app tracing is automatically enabled in non-production environments if NewRelic is present. Cross-app tracing has been tested and found to have no impact on performance or functionality. This PR turns on cross-app tracing for all environments.
> Enable NewRelic cross app tracing by default

- docs/api_specification/README.md
- docs/utilities/add_toc.rb
…(and fix default path in `add_doc.rb` in passing).
GitHub seems to be having trouble with the diff, but as far as I can tell the GFM syntax is valid.
> Rearrange API documentation for Release 3

- docs/api_specification/README.md
Am leaving the release number alone as this is happening on the same day and the fix is minor, with no API alterations.
> Replace legacy LNZL references with generic sentences

- CHANGELOG.md
- Gemfile.lock
- docs/rdoc/classes/Hoodoo.html
- docs/rdoc/classes/Hoodoo/ActiveRecord/Finder.html
- docs/rdoc/created.rid
- lib/hoodoo/active/active_record/finder.rb
- lib/hoodoo/version.rb
- spec/active/active_record/finder_spec.rb
Delayed by GitHub outage - final fix, which is more serious as it caused problems with subclasses of the Hoodoo AR Base module rather than direct inclusions. Again, explicit test coverage reproducing the fault was added prior to fix. 1.12.1 was yanked from RubyGems to avoid client breakage.
> Hopefully final hotfix for Hoodoo::...::Base subclasses and search-with

- guides_0300_active_record.md
The "service implementation" section had Show, List and Create sections, but not Update or Delete. These have been added, along with a header for the idiomatic rendering method given as an example.
> Add some missing sections.

- spec/services/services/session_spec.rb
There was a single line in the revised Session implementation which had managed to escape code coverage. Addressed.
> Code coverage bump.

- lib/hoodoo/client/endpoint/endpoints/auto_session.rb
- spec/client/client_spec.rb
When errors were present in the response that were *not* "invalid session", Client would nonetheless reacquire a session and retry (typically getting the same error back the second time too). This is obviously inefficient and risky (it might cause side effects twice despite the error, depending on the nature of the API being called).
> Fix for Hoodoo::Client.

- lib/hoodoo/services/discovery/discoverers/by_drb/by_drb.rb
- lib/hoodoo/services/middleware/middleware.rb
- spec/services/discovery/discoverers/by_drb/by_drb_spec.rb
- spec/transient_store/transient_store/mocks/redis_spec.rb
When trying to create a service like the bare metal example on the front page of http://hoodoo.cloud, but with two resources inside the service unit where one called another on should-be-local inter-resource call, a few things didn't quite work properly:
* As usual it tried to run up with the ByDRb discoverer.
* DRb server tried to launch but we weren't using `bundler` so it failed.
* Working around by using a `Gemfile` and Bundler yielded a crash in middleware as `CGI` wasn't recognised as a constant.
* Manually `require`-ing `cgi` led to a cannot-find-resource error because the lack of a discovered host/port meant no service announcements were made, so even the local resources were not known about internally.
Resolved through the following changes:
* Have by-DRb discoverer try to launch …
> Various fixes revealed by "bare metal" service creation

- Gemfile.lock
- hoodoo.gemspec
- lib/hoodoo/services/middleware/exception_reporting/reporters/airbrake_reporter.rb
- spec/services/middleware/exception_reporting/reporters/airbrake_reporter_spec.rb
- spec/spec_helper.rb
Airbrake (at least under Ruby 2.4.2) can attempt to modify a frozen Hash. It also attempts to set the backtrace in exceptions under some circumstances, again breaking if they're frozen. Test coverage added as proof.
Drive-by bump of Raygun gem to V2, which has no relevant breaking changes in its change log.
> Airbrake 6->7 and Airbrake bug work-around

- README.md
Update link from pond’s GH pages to loyaltynz. Most likely a left-over from hoodoo being open-sourced.
> Update readme link for gh-pages branch

- lib/hoodoo/client/endpoint/endpoint.rb
- spec/client/paginated_enumeration_spec.rb
Query strings providing things like offset or limit parameters for lists are processed within Hoodoo from URIs and into hashes, thus being expressed with String keys generally. Likewise, inter-resource calls work in that domain. Hoodoo::Client however, at the top level, is often called with Symbols. At the interface between the caller-facing layer and the internal implementation, these are "stringified".
The mixin providing `enumerate_all` functionality expected String keys when working with `offset` in a query hash and would produce odd results if a Symbol was used. So, instead of doing a `dup` on the given query hash, it is Stringified instead, producing a duplicate as a side effect. This solves both problems.
Test coverage is included. The strange-looking section names arise because of …
> Fix subtle edge case with enumerate_all and :offset-vs-'offset'

- CHANGELOG.md
- Gemfile.lock
- lib/hoodoo/presenters/base_dsl.rb
- lib/hoodoo/presenters/types/hash.rb
- lib/hoodoo/version.rb
- spec/presenters/types/hash_spec.rb
Fixes a bug in `Hoodoo::Presenters::Hash`. Previously, invoking the `key` method with a block would force the type to be `Hoodoo::Presenters::Object`, even when the type was set to `hash` (which may also accept a block). This would then break the nested schema in the block as Object does not support the `key`/`keys` methods.
> Support `hash` as a valid property type for keys.

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
Introduce a long explanation about how to deploy a new Gem release to Rubygems, using GitHub UI, Travis CI, and its triggers.
> DS-2034 Introduce guidelines about deploying a new release to RubyGems

- CHANGELOG.md
- Gemfile.lock
- docs/api_specification/README.md
- lib/hoodoo/version.rb
Updated documentation for the new `platform.downstream_error` error code introduced in the previous release
> FT-1114 Updated docs

- CHANGELOG.md
- Gemfile.lock
- hoodoo.gemspec
- lib/hoodoo/version.rb
[DS-2723](https://loyaltynz.atlassian.net/browse/DS-2723)
Dalli 2.7.11 is the one mentioned in CVE-2022-4064, but the current version requirements don't stop any dependent projects using that version. For example service_fly_buys_purchase ([error](https://jenkins.loyaltydevops.co.nz/blue/organizations/jenkins/Kubernetes%2Fservice_fly_buys_purchase%2FPRCheck/detail/PRCheck/37/pipeline)):
[DS-2723]: https://loyaltynz.atlassian.net/browse/DS-2723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DS-2723: disallow Dalli 2.7.x

- CHANGELOG.md
- Gemfile.lock
- lib/hoodoo/version.rb
**Base Image:** docker.loyaltydevops.co.nz/service_base_ruby:3.1.0
**Jenkins build:** https://jenkins.loyaltydevops.co.nz/job/TechOps/job/cron-jobs/job/PatchBot/job/bundle_update_dryrun/47/
- dalli 3.2.4 (was 3.2.3)
- redis 4.8.1 (was 4.8.0)
- rspec-core 3.12.1 (was 3.12.0)
- tzinfo 2.0.6 (was 2.0.5)
- activesupport 7.0.4.2 (was 7.0.4.1)
- activemodel 7.0.4.2 (was 7.0.4.1)
- activerecord 7.0.4.2 (was 7.0.4.1)
> DS-2987  Automated Monthly Patches - Feb23

- .travis.yml
- CHANGELOG.md
- Gemfile.lock
- hoodoo.gemspec
- lib/hoodoo/version.rb
[DS-3525](https://loyaltynz.atlassian.net/browse/DS-3525)
- Support projects that use ruby `3.1.2`
[DS-3525]: https://loyaltynz.atlassian.net/browse/DS-3525?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DS-3525 Support older (3.1.2) versions of ruby

- CHANGELOG.md
- Gemfile.lock
- lib/hoodoo/data/resources/caller.rb
- lib/hoodoo/version.rb
- spec/data/resources/caller_spec.rb
[FT-4004](https://loyaltynz.atlassian.net/browse/FT-4004)
Updated the `Caller` schema, added new attribute `authentication_secret_parameter_store_path` - see https://github.com/LoyaltyNZ/awg/pull/814.
Note this is backwards compatible, the new attribute is only rendered if data is supplied for it
Updated the schema and associated tests
[FT-4004]: https://loyaltynz.atlassian.net/browse/FT-4004?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FT-4004 Updated Caller, added authentication_secret_parameter_store_path

- CHANGELOG.md
- Gemfile.lock
- lib/hoodoo/version.rb
**Base Image:** docker.loyaltydevops.co.nz/service_base_ruby:3.3.0
**Jenkins build:** https://jenkins.loyaltydevops.co.nz/job/TechOps/job/cron-jobs/job/MonthlyPatching/job/bundle_update/1245/
- bigdecimal 3.1.7 (was 3.1.6) with native extensions
- rack 2.2.9 (was 2.2.8.1)
- i18n 1.14.4 (was 1.14.1)
- rdoc 6.5.1.1 (was 6.5.0)
> DS-4332  Automated Monthly Patches - Mar24

- CHANGELOG.md
- Gemfile.lock
- lib/hoodoo/version.rb
**Base Image:** docker.loyaltydevops.co.nz/service_base_ruby:3.3.0
**Jenkins build:** https://jenkins.loyaltydevops.co.nz/job/TechOps/job/cron-jobs/job/MonthlyPatching/job/bundle_update/1357/
- bigdecimal 3.1.8 (was 3.1.7) with native extensions
- timecop 0.9.9 (was 0.9.8)
- i18n 1.14.5 (was 1.14.4)
- rexml 3.2.8 (was 3.2.6)
- activesupport 7.0.8.3 (was 7.0.8.1)
- activemodel 7.0.8.3 (was 7.0.8.1)
- activerecord 7.0.8.3 (was 7.0.8.1)
> DS-4649  Automated Monthly Patches - Jun24
