guides_0200_security.md

This is the Hoodoo Guides passing mention of `X-Assume-Identity-Of`.

Mention X-Assume-Identity-Of

---

.travis.yml
_config.yml
guides_0300_active_record.md

If this makes sense, please merge. The RDoc links won't work until it's live and merged, but you can get a sneak preview here:
https://cdn.rawgit.com/LoyaltyNZ/hoodoo/master/docs/rdoc/classes/Hoodoo/ActiveRecord/ManuallyDated.html

Add 'manually dated' information

---

guides_0600_exception_reporting.md

See https://github.com/LoyaltyNZ/hoodoo/pull/136.

Describe Hoodoo's new exception handling 'contextual_report' mechanism

---

guides_0100_fundamentals.md

Address issue #127 - documentation improvement

---

docs/api_specification/README.md
lib/hoodoo/active/active_record/finder.rb
lib/hoodoo/client/augmented_array.rb
lib/hoodoo/client/client.rb
lib/hoodoo/client/endpoint/endpoints/http_based.rb
lib/hoodoo/services/middleware/middleware.rb
lib/hoodoo/services/services/response.rb
spec/active/active_record/finder_spec.rb
spec/client/client_spec.rb
spec/services/middleware/middleware_exotic_communication_spec.rb
spec/services/middleware/middleware_multi_local_spec.rb
spec/services/middleware/middleware_multi_remote_spec.rb
spec/services/services/response_spec.rb

Some persistence layers can count slowly, but estimate quickly. Provide a mechanism to access this.

Add estimated dataset size feature

---

CHANGELOG.md
Gemfile.lock
docs/rdoc/classes/Hoodoo.html
docs/rdoc/classes/Hoodoo/Monkey/Patch/NewRelicTracedAMQP.html
docs/rdoc/classes/Hoodoo/Monkey/Patch/NewRelicTracedAMQP/AMQPNewRelicRequestWrapper.html
docs/rdoc/classes/Hoodoo/Monkey/Patch/NewRelicTracedAMQP/AMQPNewRelicResponseWrapper.html
docs/rdoc/classes/Hoodoo/Monkey/Patch/NewRelicTracedAMQP/InstanceExtensions.html
docs/rdoc/created.rid
hoodoo.gemspec
lib/hoodoo/version.rb
spec/active/active_record/finder_spec.rb

See `CHANGELOG.md` diff for details.

Version 1.8.2

---

lib/hoodoo/client/client.rb
lib/hoodoo/services/services/interface.rb

Fix some documentation (RDoc) related to embeds

---

Gemfile.lock
guides_1100_upgrading.md

Guide for Hoodoo v1 to v2, along with its dependency updates and service shell changes.

Add migration guide

---

guides_1100_upgrading.md

Add migration help for Datadog 0.10.x->0.11.x.

Draft documentation covering Datadog API changes

---

guides_1000_env_vars.md
guides_1100_upgrading.md

Also adds a note to clarify environment variable cacheing behaviour.

Add information on new 2.3.0 feature

---

CHANGELOG.md
Gemfile.lock
hoodoo.gemspec
lib/hoodoo/presenters/base.rb
lib/hoodoo/services/middleware/middleware.rb
lib/hoodoo/version.rb
spec/presenters/base_spec.rb
spec/services/middleware/middleware_spec.rb

* CHANGELOG.md for details
* RDoc alterations to follow on `master` prior to pushing the 2.3.1 tag.

Workshop-found fixes

---

CHANGELOG.md
Gemfile.lock
lib/hoodoo/utilities/utilities.rb
lib/hoodoo/version.rb
spec/utilities/utilities_spec.rb

Omits RDoc updates in this PR because the updated bundle caused a lot of file changes, all of which appear to be white space only. Will commit that in a separate PR to follow.
(EDIT): See #257.

Allow Date instances in #rationalise_datetime

---

.travis.yml
CHANGELOG.md
Gemfile.lock
lib/hoodoo/presenters/types/hash.rb
lib/hoodoo/version.rb
spec/utilities/utilities_spec.rb

Removed the use of Rails method `blank?` & replaced it with a ruby only equivalent code snippet

Bug fix, removed dependency on the Rails  `blank?` method.

---

.gitignore
CHANGELOG.md
Gemfile.lock
docs/api_specification/README.md
lib/hoodoo/client/headers.rb
lib/hoodoo/version.rb
spec/client/client_spec.rb

Required by:
* https://github.com/LoyaltyNZ/service_fly_buys_member/pull/136
* https://github.com/LoyaltyNZ/flybuys/pull/3376

Add HTTP header X-Disable-Downstream-Sync

---

.travis.yml
CHANGELOG.md
spec/spec_helper.rb

Postgres 13.3 upgrade [FT-811](https://loyaltynz.atlassian.net/browse/FT-811)

FT-811 Postgres 13.3 upgrade

---

.travis.yml
CHANGELOG.md
spec/spec_helper.rb

- Postgres 13.3 upgrade [FT-874](https://loyaltynz.atlassian.net/browse/FT-874)

FT-874 Post brownout christmas 2021 merge

---

.travis.yml

I removed the `jobs` section. It looks like the `script` gets overridden if the matrix results to just one job. In this case, it was because only one `rvm` was specified (https://config.travis-ci.com/matrix_expansion).

Fix Lukas' CI

---

.travis.yml
CHANGELOG.md
Gemfile.lock
README.md
lib/hoodoo/active/active_model/uuid_validator.rb
lib/hoodoo/version.rb
spec/active/active_record/creator_spec.rb
spec/active/active_record/error_mapping_spec.rb
spec/active/active_record/support_spec.rb
spec/active/active_record/uuid_spec.rb
spec/spec_helper.rb

https://loyaltynz.atlassian.net/browse/DS-1930
Master branch was failing after activerecord 7 upgrade. Travis was also false positive as the specs were skipped. Everything is fixed now

[DS-1930] Fixed travis & ensure spec running

---

README.md

Minor changes to make reference to the current Gem version v3.1.*

DS-2034 Update README

---

CHANGELOG.md
Gemfile.lock
lib/hoodoo/version.rb

Testing the versioning process for Hoodoo

DS-2024 Test Hoodoo versioning

---

CHANGELOG.md
Gemfile.lock
lib/hoodoo/errors/error_descriptions.rb
lib/hoodoo/version.rb

Jira card: [FT-1114](https://loyaltynz.atlassian.net/browse/FT-1114)
- Add a new platform error description: 'downstream_error'

[FT-1114] add 'downstream error' to error_descriptions.rb

---

CHANGELOG.md
Gemfile.lock
lib/hoodoo/version.rb

**Base Image:** docker.loyaltydevops.co.nz/service_base_ruby:3.1.0
**Jenkins build:** https://jenkins.loyaltydevops.co.nz/job/TechOps/job/cron-jobs/job/MonthlyPatching/job/bundle_update/374/
- addressable 2.8.3 (was 2.8.2)

DS-3188  Automated Monthly Patches - Apr23

---

CHANGELOG.md
Gemfile.lock
lib/hoodoo/version.rb

**Base Image:** docker.loyaltydevops.co.nz/service_base_ruby:3.1.0
**Jenkins build:** https://jenkins.loyaltydevops.co.nz/job/TechOps/job/cron-jobs/job/MonthlyPatching/job/bundle_update/549/
- thor 1.2.2 (was 1.2.1)
- activesupport 7.0.5 (was 7.0.4.3)
- activemodel 7.0.5 (was 7.0.4.3)
- activerecord 7.0.5 (was 7.0.4.3)

DS-3352  Automated Monthly Patches - Jun23

---

CHANGELOG.md
Gemfile.lock
lib/hoodoo/version.rb

**Base Image:** docker.loyaltydevops.co.nz/service_base_ruby:3.1.0
**Jenkins build:** https://jenkins.loyaltydevops.co.nz/job/TechOps/job/cron-jobs/job/MonthlyPatching/job/bundle_update/604/
- rspec-support 3.12.1 (was 3.12.0)
- activesupport 7.0.6 (was 7.0.5)
- activemodel 7.0.6 (was 7.0.5)
- activerecord 7.0.6 (was 7.0.5)

DS-3435  Automated Monthly Patches - Jul23

---

CHANGELOG.md
Gemfile.lock
lib/hoodoo/version.rb

**Jenkins build:** https://jenkins.loyaltydevops.co.nz/job/TechOps/job/cron-jobs/job/MonthlyPatching/job/bundle_update/714/
- rack 2.2.8 (was 2.2.7)
- rexml 3.2.6 (was 3.2.5)
- addressable 2.8.5 (was 2.8.4)
- rspec-mocks 3.12.6 (was 3.12.5)

DS-3561  Automated Monthly Patches - Aug23

---

CHANGELOG.md
Gemfile.lock
lib/hoodoo/version.rb

**Jenkins build:** https://jenkins.loyaltydevops.co.nz/job/TechOps/job/cron-jobs/job/MonthlyPatching/job/bundle_update/871/
- ffi 1.16.3 (was 1.16.2) with native extensions
- psych 5.1.1.1 (was 5.1.0) with native extensions
- irb 1.8.3 (was 1.8.1)

DS-3863  Automated Monthly Patches - Nov23

---

CHANGELOG.md
Gemfile.lock
lib/hoodoo/version.rb

**Jenkins build:** https://jenkins.loyaltydevops.co.nz/job/TechOps/job/cron-jobs/job/MonthlyPatching/job/bundle_update/924/
- public_suffix 5.0.4 (was 5.0.3)
- stringio 3.0.9 (was 3.0.8) with native extensions

DS-3944  Automated Monthly Patches - Dec23

---

CHANGELOG.md
Gemfile.lock
lib/hoodoo/version.rb

**Jenkins build:** https://jenkins.loyaltydevops.co.nz/job/TechOps/job/cron-jobs/job/MonthlyPatching/job/bundle_update/978/
- addressable 2.8.6 (was 2.8.5)
- psych 5.1.2 (was 5.1.1.1) with native extensions

DS-4037  Automated Monthly Patches - Jan24

---

CHANGELOG.md
Gemfile.lock
hoodoo.gemspec
lib/hoodoo/version.rb

**Jenkins build:** https://jenkins.loyaltydevops.co.nz/job/TechOps/job/cron-jobs/job/MonthlyPatching/job/bundle_update/1082/
- concurrent-ruby 1.2.3 (was 1.2.2)
- dalli 3.2.7 (was 3.2.6)
- simplecov-rcov 0.3.7 (was 0.3.3)

DS-4088  Automated Monthly Patches - Jan24

---

CHANGELOG.md
Gemfile.lock
lib/hoodoo/version.rb

**Jenkins build:** https://jenkins.loyaltydevops.co.nz/job/TechOps/job/cron-jobs/job/MonthlyPatching/job/bundle_update/1136/
- diff-lcs 1.5.1 (was 1.5.0)
- rspec-support 3.12.2 (was 3.12.1)
- rspec-core 3.12.3 (was 3.12.2)
- rspec-expectations 3.12.4 (was 3.12.3)
- rspec-mocks 3.12.7 (was 3.12.6)

DS-4147  Automated Monthly Patches - Feb24

---

CHANGELOG.md
Gemfile.lock
lib/hoodoo/version.rb

**Base Image:** docker.loyaltydevops.co.nz/service_base_ruby:3.3.0
**Jenkins build:** https://jenkins.loyaltydevops.co.nz/job/TechOps/job/cron-jobs/job/MonthlyPatching/job/bundle_update/1301/
- public_suffix 5.0.5 (was 5.0.4)

DS-4502  Automated Monthly Patches - May24
